alias is='sudo apt-get install'
alias isd='sudo dpkg -i'
alias ism='sudo apt-get install -f'
alias isb='sudo apt-get install --fix-broken'
alias uis='sudo apt-get remove'
alias autorm='sudo apt-get autoremove'
alias ud='sudo apt-get update'

alias av='source activate'
alias dv='conda deactivate'
alias cis='conda install'
alias pis='pip install'

alias g='git clone'
alias gp='git pull'
alias dogit='python /home/charlie/.complete_git_commit.py'

alias dl='cd /home/charlie/Downloads'
alias dm='cd /home/charlie/Documents'
alias dk='cd /home/charlie/Desktop'
alias dp='cd /home/charlie/Documents/Projects'
alias dg='cd /home/charlie/Documents/GitHub_repos'
alias snip='cd /home/charlie/.vim/additional_plugins/vim-snippets/UltiSnips'

alias LS='ls'
alias s='ls'
alias S='ls'
alias sl='ls'
alias SL='ls'
alias l='ls'
alias L='ls'
alias ks='ls'
alias sk='ls'
alias KS='ls'
alias SK='ls'
alias lks='ls'
alias LKS='ls'
alias kls='ls'
alias KLS='ls'

alias ff='sudo find / -name'

alias eb='vim /home/charlie/.bash_aliases'

alias ctx='python /home/charlie/.compile_tex_file.py'
alias p2e='python /home/charlie/.pdf_to_eps.py'
alias v='vim'
alias p='python'
alias o='octave --no-gui'
alias t='touch'
alias img='sudo fbi'

alias nwr='sudo service network-manager restart'

alias spt='expect /home/charlie/.connect_to_ParisTech_server.sh'
alias sptd='expect /home/charlie/.download_from_ParisTech_server.sh'
alias sptu='expect /home/charlie/.upload_to_ParisTech_server.sh'
alias sls='expect /home/charlie/.connect_to_426_server.sh'
alias slsd='expect /home/charlie/.download_from_426_server.sh'
alias slsu='expect /home/charlie/.upload_to_426_server.sh'

