alias is='sudo apt-get install'
alias isd='sudo dpkg -i'
alias ism='sudo apt-get install -f'
alias isb='sudo apt-get install --fix-broken'
alias uis='sudo apt-get remove'
alias autorm='sudo apt-get autoremove'
alias ud='sudo apt-get update'

alias av='source activate'
alias dv='conda deactivate'
alias cis='conda install'
alias pis='pip install'

alias g='git clone'
alias gp='git pull'
alias dogit='python ~/.complete_git_commit.py'

alias ..='cd ..'
alias ,,='cd ..'
alias ...='cd ../..'
alias ,,,='cd ../..'
alias ....='cd ../../..'
alias ,,,,='cd ../../..'
alias c='cd'
alias home='cd ~'
alias dl='cd ~/Downloads'
alias dm='cd ~/Documents'
alias dk='cd ~/Desktop'
alias dp='cd ~/Documents/Projects'
alias dg='cd ~/Documents/GitHub_repos'
alias tst='cd ~/Testground'
alias bingo='cd ~/Projects'
alias num='ls -l | grep "^-" | wc -l'
alias snip='cd ~/.vim/additional_plugins/vim-snippets/UltiSnips'

alias LS='ls'
alias s='ls'
alias S='ls'
alias sl='ls'
alias SL='ls'
alias l='ls'
alias L='ls'
alias ks='ls'
alias sk='ls'
alias KS='ls'
alias SK='ls'
alias lks='ls'
alias LKS='ls'
alias kls='ls'
alias KLS='ls'
alias la='ls -a'
alias ll='ls -l'

alias ff='sudo find / -name'

alias eb='vim -X ~/.bash_aliases'
alias eh='sudo vim -X /etc/hosts'
alias work='vim -X ~/work.txt'

alias j2p='jupyter nbconvert --to script'
alias ctx='python ~/.compile_tex_file.py'
alias p2e='python ~/.pdf_to_eps.py'

alias v='vim -X'
alias p='python'
alias t='touch'
alias tm='tmux attach -t'

alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -i'

alias nwr='sudo service network-manager restart'

